// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NadrojAPI.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NadrojAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221122005126_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NadrojAPI.Models.TournamentModel", b =>
                {
                    b.Property<int>("tournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tournamentId"));

                    b.Property<string>("nickName")
                        .HasColumnType("text");

                    b.Property<int>("numEntries")
                        .HasColumnType("integer");

                    b.Property<double>("prizePool")
                        .HasColumnType("double precision");

                    b.HasKey("tournamentId");

                    b.ToTable("tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
